set(__QT_DEPLOY_TARGET_oj_FILE E:/csqt/build-mingw/oj.exe)
set(__QT_DEPLOY_TARGET_oj_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_oj_RUNTIME_DLLS D:/QT/6.11.0/mingw_64/bin/Qt6Widgets.dll;D:/QT/6.11.0/mingw_64/bin/Qt6Sql.dll;D:/QT/6.11.0/mingw_64/bin/Qt6Multimedia.dll;D:/QT/6.11.0/mingw_64/bin/Qt6Network.dll;D:/QT/6.11.0/mingw_64/bin/Qt6Gui.dll;D:/QT/6.11.0/mingw_64/bin/Qt6Concurrent.dll;D:/QT/6.11.0/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_oj_parser_tests_FILE E:/csqt/build-mingw/oj_parser_tests.exe)
set(__QT_DEPLOY_TARGET_oj_parser_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_oj_parser_tests_RUNTIME_DLLS D:/QT/6.11.0/mingw_64/bin/Qt6Test.dll;D:/QT/6.11.0/mingw_64/bin/Qt6Core.dll)
